apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres-postgresql:5432/postgres"
