apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  annotations:
    app.quarkus.io/quarkus-version: 3.14.4
    app.quarkus.io/build-timestamp: 2024-09-20 - 09:02:03 +0000
  labels:
    app.kubernetes.io/name: simple-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: simple-app
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.14.4
        app.quarkus.io/build-timestamp: 2024-09-20 - 09:02:03 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: simple-app
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: simple-app:0.0.1
          imagePullPolicy: Never
          name: simple-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
