apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: services
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
